Resources:
  ProductsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: productId
          AttributeType: S
      KeySchema:
        - AttributeName: productId
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
      TableName: ${param:PRODUCT_TABLE}

Outputs:
    ProductsTableAccessOutput:
      Value: !GetAtt ProductsTable.Arn
      Export:
        Name: ${param:PRODUCT_TABLE_ACCESS_ARN}
