Resources:
  UsersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: userId
          AttributeType: S
      KeySchema:
        - AttributeName: userId
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
      TableName: ${self:custom.USER_TABLE}

Outputs:
    UsersTableAccessOutput:
      Value: !GetAtt UsersTable.Arn
      Export:
        Name: user-table-access-${self:custom.stage}