org: ${file(../../../default.yml):org}
app: ${file(../../../default.yml):app}
frameworkVersion: ${file(../../../default.yml):frameworkVersion}

service: user-mng
params: ${file(../../../default.yml):params}
custom: ${file(../../../default.yml):custom}

provider:
  name: aws
  runtime: nodejs16.x
  region: ${self:custom.aws_region}
  deploymentBucket: 
    name: ${param:DEPLOYMENT_BUCKET_NAME}-${self:service}
    # Prevents public access via ACLs or bucket policies (default: false)
    # Note: the deployment bucket is not public by default. These are additional ACLs.
    blockPublicAccess: true
  environment:
    TABLE: ${param:USER_TABLE}
    STATE: ${sls:stage}

functions:
  create:
    handler: handler.createUser
    events:
      - http:
          path: users
          method: post
          cors: true
    role: TablePutRole

  list:
    handler: handler.getListUser
    events:
      - http:
          path: users
          method: get
          cors: true
    role: TableListRole
        
  get:
    handler: handler.getUser
    events:
      - http:
          path: users/{id}
          method: get
          cors: true
    role: TableGetRole
        
  update:
    handler: handler.updateUser
    events:
      - http:
          path: users/{id}
          method: put
          cors: true
    role: TableUpdateRole

  delete:
    handler: handler.deleteUser
    events:
      - http:
          path: users/{id}
          method: delete
          cors: true 
    role: TableDeleteRole

resources:
  - ${file(./resources/dynamoDB.yml)}
  - ${file(./resources/roles.yml)}

plugins: ${file(../../../default.yml):plugins}
